---
name: Remind-Client
version: 0.01
author:
  - 'Mike Kelly <pioto@pioto.org>'
abstract: class for working with remind's daemon mode
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Remind-Client
  license: http://dev.perl.org/licenses/
  repository: http://git.pioto.org/gitweb/Remind-Client.git
build_requires:
  File::Temp: 0.14
  Module::Build: 0.28
  POSIX: 0
  Test::More: 0.8101
  Test::NoWarnings: 0
  Test::Warn: 0
requires:
  Carp: 0
  File::HomeDir: 0.5
  IO::Handle: 0
  IPC::Open2: 0
configure_requires:
  Module::Build: 0.28
provides:
  Remind::Client:
    file: lib/Remind/Client.pm
    version: 0.01
  Remind::Client::libnotify:
    file: lib/Remind/Client/libnotify.pm
    version: 0.01
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
